# MMLogger性能测试配置文件
---
global:
  output_file: "benchmark_results.csv"  # 全局结果输出文件
  append_output: true                   # 是否追加到现有文件
  verbose_output: true                  # 是否显示详细输出

test_suites:
  - name: "基础性能比较"
    description: "比较不同日志器的基本性能特征"
    tests:
        #- id: "base_stdout"
        #  name: "标准输出日志器"
        #  logger_type: "Stdout"
        #  enable_console: true
        #  enable_file: false
        #  log_level: "info"
        #  num_threads: 4
        #  logs_per_thread: 100000
        #  log_msg_size: 128
        #  log_rate: 0  # 尽可能快
        #  debug_pct: 10
        #  info_pct: 60
        #  warn_pct: 20
        #  error_pct: 10
        #  warmup_seconds: 2
        #  test_duration: 10
        #  cooldown_seconds: 2

      - id: "base_glog"
        name: "GLog日志器_console"
        logger_type: "GLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

      - id: "base_glog_no_console"
        name: "GLog日志器"
        logger_type: "GLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

      - id: "base_optimized_console"
        name: "优化GLog日志器"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

      - id: "base_optimized_no_console"
        name: "优化GLog日志器"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
