# MMLogger Performance Test Configuration
---
global:
  output_file: "benchmark_results.csv"  # Global results output file
  append_output: true                   # Append to existing file
  verbose_output: true                  # Enable detailed output

test_suites:
  - name: "Basic Performance Comparison"
    description: "Compare the basic performance characteristics of different logger implementations"
    tests:
      - id: "stdout_basic"
        name: "Stdout Logger (Basic)"
        logger_type: "Stdout"
        enable_console: true
        enable_file: false
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # As fast as possible
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "glog_basic"
        name: "GLog Logger (Basic)"
        logger_type: "GLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "optimized_basic"
        name: "OptimizedGLog Logger (Basic)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

  - name: "Threading Scalability Tests"
    description: "Test how different thread counts affect performance"
    tests:
      - id: "thread_1"
        name: "Single Thread"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 1
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 2
        pool_size: 20000
        test_duration: 10

      - id: "thread_4"
        name: "4 Threads"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "thread_16"
        name: "16 Threads"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 16
        logs_per_thread: 50000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 20000
        num_workers: 8
        pool_size: 40000
        test_duration: 10

  - name: "Message Size Tests"
    description: "Test impact of different message sizes"
    tests:
      - id: "size_small"
        name: "Small Messages (64 bytes)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 64
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "size_medium"
        name: "Medium Messages (512 bytes)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 512
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "size_large"
        name: "Large Messages (2048 bytes)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 2048
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

  - name: "Output Destination Tests"
    description: "Test impact of different output destinations"
    tests:
      - id: "output_console_only"
        name: "Console Output Only"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: false
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "output_file_only"
        name: "File Output Only"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/output"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "output_both"
        name: "Both Console and File Output"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/output"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

  - name: "Optimization Parameter Tests"
    description: "Test impact of different optimization parameters"
    tests:
      - id: "opt_small_batch"
        name: "Small Batch Size (50)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 50
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "opt_large_batch"
        name: "Large Batch Size (1000)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 1000
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "opt_large_queue"
        name: "Large Queue Capacity (50000)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 50000
        num_workers: 4
        pool_size: 60000
        test_duration: 10

      - id: "opt_many_workers"
        name: "Many Worker Threads (8)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 8
        pool_size: 20000
        test_duration: 10

  - name: "Production Configuration Tests"
    description: "Test recommended production configurations"
    tests:
      - id: "prod_standard"
        name: "Standard Production Config"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/prod"
        log_level: "info"
        num_threads: 8
        logs_per_thread: 100000
        log_msg_size: 256
        log_rate: 0
        batch_size: 500
        queue_capacity: 20000
        num_workers: 4
        pool_size: 40000
        test_duration: 20

      - id: "prod_high_perf"
        name: "High Performance Production Config"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/prod"
        log_level: "info"
        num_threads: 16
        logs_per_thread: 100000
        log_msg_size: 256
        log_rate: 0
        batch_size: 1000
        queue_capacity: 50000
        num_workers: 8
        pool_size: 100000
        test_duration: 20
