# MMLogger Performance Test Configuration
---
global:
  output_file: "benchmark_results.csv"  # Global results output file
  append_output: true                   # Append to existing file
  verbose_output: true                  # Enable detailed output

test_suites:
  - name: "Basic Performance Comparison"
    description: "Compare the basic performance characteristics of different logger implementations"
    tests:
      - id: "stdout_basic"
        name: "Stdout Logger (Basic)"
        logger_type: "Stdout"
        enable_console: true
        enable_file: false
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # As fast as possible
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "glog_basic_console_false"
        name: "GLog Logger (Basic)"
        logger_type: "GLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "glog_basic"
        name: "GLog Logger (Basic)"
        logger_type: "GLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "optimized_basic_console_false"
        name: "OptimizedGLog Logger (Basic)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true

      - id: "optimized_basic"
        name: "OptimizedGLog Logger (Basic)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2
        measure_latency: true
