# MMLogger性能测试配置文件
---
global:
  output_file: "benchmark_results.csv"  # 全局结果输出文件
  append_output: true                   # 是否追加到现有文件
  verbose_output: true                  # 是否显示详细输出

test_suites:
  - name: "基础性能比较"
    description: "比较不同日志器的基本性能特征"
    tests:
      - id: "base_stdout"
        name: "标准输出日志器"
        logger_type: "Stdout"
        enable_console: true
        enable_file: false
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

      - id: "base_glog"
        name: "GLog日志器"
        logger_type: "GLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/glog"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

      - id: "base_optimized"
        name: "优化GLog日志器"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/optimized"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0  # 尽可能快
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        warmup_seconds: 2
        test_duration: 10
        cooldown_seconds: 2

  - name: "线程扩展性测试"
    description: "测试不同线程数量下的性能表现"
    tests:
      - id: "threads_1"
        name: "单线程"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 1
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "threads_4"
        name: "4线程"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "threads_16"
        name: "16线程"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/threads"
        log_level: "info"
        num_threads: 16
        logs_per_thread: 50000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

  - name: "消息大小测试"
    description: "测试不同消息大小对性能的影响"
    tests:
      - id: "size_small"
        name: "小消息(64字节)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 64
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "size_medium"
        name: "中等消息(512字节)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 512
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "size_large"
        name: "大消息(2048字节)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/size"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 2048
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

  - name: "输出目标测试"
    description: "测试不同输出目标对性能的影响"
    tests:
      - id: "output_console_only"
        name: "仅控制台输出"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: false
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "output_file_only"
        name: "仅文件输出"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/output"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "output_both"
        name: "控制台和文件同时输出"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/output"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

  - name: "优化参数测试"
    description: "测试不同优化参数对性能的影响"
    tests:
      - id: "opt_batch_small"
        name: "小批处理(50)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 50
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "opt_batch_large"
        name: "大批处理(1000)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 1000
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 10

      - id: "opt_queue_large"
        name: "大队列(50000)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 50000
        num_workers: 4
        pool_size: 60000
        test_duration: 10

      - id: "opt_workers_many"
        name: "多工作线程(8)"
        logger_type: "OptimizedGLog"
        enable_console: true
        enable_file: true
        log_file_path: "./logs/opt"
        log_level: "info"
        num_threads: 4
        logs_per_thread: 100000
        log_msg_size: 128
        log_rate: 0
        batch_size: 200
        queue_capacity: 10000
        num_workers: 8
        pool_size: 20000
        test_duration: 10

  - name: "真实负载测试"
    description: "模拟真实应用场景下的日志负载"
    tests:
      - id: "real_low_rate"
        name: "低速率均匀日志"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/real"
        log_level: "info"
        num_threads: 8
        logs_per_thread: 50000
        log_msg_size: 256
        log_rate: 10000  # 每秒10000条日志
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 20

      - id: "real_burst"
        name: "突发日志"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/real"
        log_level: "info"
        num_threads: 16  # 更多线程模拟突发
        logs_per_thread: 10000
        log_msg_size: 256
        log_rate: 0  # 尽可能快速突发
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 500
        queue_capacity: 20000
        num_workers: 4
        pool_size: 30000
        test_duration: 5  # 短时间突发

      - id: "real_mixed_size"
        name: "混合大小日志"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/real"
        log_level: "info"
        num_threads: 8
        logs_per_thread: 50000
        log_msg_size: -1  # 特殊值，表示使用混合大小
        mixed_size_min: 64
        mixed_size_max: 4096
        log_rate: 5000
        debug_pct: 10
        info_pct: 60
        warn_pct: 20
        error_pct: 10
        batch_size: 200
        queue_capacity: 10000
        num_workers: 4
        pool_size: 20000
        test_duration: 20

  - name: "生产环境推荐配置测试"
    description: "测试推荐给生产环境的配置"
    tests:
      - id: "prod_config_1"
        name: "生产配置1(标准)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/prod"
        log_level: "info"
        num_threads: 8
        logs_per_thread: 100000
        log_msg_size: 256
        log_rate: 0
        batch_size: 500
        queue_capacity: 20000
        num_workers: 4
        pool_size: 40000
        test_duration: 20

      - id: "prod_config_2"
        name: "生产配置2(高性能)"
        logger_type: "OptimizedGLog"
        enable_console: false
        enable_file: true
        log_file_path: "./logs/prod"
        log_level: "info"
        num_threads: 16
        logs_per_thread: 100000
        log_msg_size: 256
        log_rate: 0
        batch_size: 1000
        queue_capacity: 50000
        num_workers: 8
        pool_size: 100000
        test_duration: 20
